# Generated by Django 5.0.7 on 2024-07-27 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='sobre',
            field=models.TextField(null=True),
        ),
    ]
