# Generated by Django 5.1 on 2024-08-24 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0003_aluno_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='bairro',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='aluno',
            name='cep',
            field=models.CharField(default=0, max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aluno',
            name='cidade',
            field=models.CharField(default='Boca da Mata', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aluno',
            name='cpf',
            field=models.CharField(default=0, max_length=11, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aluno',
            name='email',
            field=models.EmailField(default='fulaninho@gmail.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aluno',
            name='endereco',
            field=models.CharField(default='rua do girassol', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aluno',
            name='estado',
            field=models.CharField(default='Alagoas', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aluno',
            name='logradouro',
            field=models.CharField(default='Rua da pista', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aluno',
            name='nome_mae',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='aluno',
            name='nome_pai',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='aluno',
            name='numero',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='aluno',
            name='pais',
            field=models.CharField(default='Brasil', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aluno',
            name='sexo',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], default='Mulher', max_length=1),
            preserve_default=False,
        ),
    ]
