# Generated by Django 5.1 on 2024-08-24 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0004_aluno_bairro_aluno_cep_aluno_cidade_aluno_cpf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='cpf',
            field=models.CharField(max_length=11),
        ),
    ]
